[character]
use_symbol_for_status = true
# success_symbol = "[âœ]"
# error_symbol = "[âœ–]"
# error_symbol = "  âœ—"
# symbol = "âŸ"
symbol = "âœ"
style_success = "bold #00A652"
style_failure = "bold #df382c"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[battery.display]
threshold = 10
style = "bold red"


[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
# prefix = " ğŸ“‚ï¸ "

[username]
style_user = "bold dimmed blue"
show_always = true
